user:
  name:
    maximum_length: 50
  email:
    maximum_length: 50
  password:
    default_password: "123456"
    minimum_length: 6
  reset:
    pass_word: 2
  avatar:
    size_default: "80x80"
sessions:
  check: "1"
per_page:
  config: 4
